-- Auto-generated by pipeline/sync_brain.py
insert into brain_pages (slug, type, title, compiled_truth, timeline_md, tags, frontmatter)
values (
  'reports/weekly-market-digest',
  'source',
  'Weekly Market Digest 2026-04-12T06:46:52Z',
  'Weekly idol market digest generated on 2026-04-12T06:46:52Z. Top group: 幻獣. Top member: 小豆 Azuki. Market temperature: 61.3. Rising stars: 燁水 Yomizu, DeDe, Meya, Neko, 稲妻莉央. Heat drop watch: none.',
  '- 2026-04-12T06:46:52Z: weekly market digest generated
- Highlight top group: 幻獣
- Highlight top member: 小豆 Azuki
- Rising stars: 燁水 Yomizu, DeDe, Meya, Neko, 稲妻莉央',
  array['idol-platform','weekly-digest','ai-insights','secbrain'],
  '{"generated_at": "2026-04-12T06:46:52Z", "top_group": "幻獣", "top_member": "小豆 Azuki", "market_temperature": "61.3", "rising_stars": ["燁水 Yomizu", "DeDe", "Meya", "Neko", "稲妻莉央"], "heat_drop": []}'::jsonb
)
on conflict (slug) do update set
  title = excluded.title,
  compiled_truth = excluded.compiled_truth,
  timeline_md = excluded.timeline_md,
  tags = excluded.tags,
  frontmatter = excluded.frontmatter,
  updated_at = now();

insert into brain_timeline_entries (page_slug, entry_date, summary, detail, source)
values (
  'reports/weekly-market-digest',
  '2026-04-12T06:46:52Z',
  'Weekly digest refreshed: 2026-04-12T06:46:52Z',
  'Weekly idol market digest generated on 2026-04-12T06:46:52Z. Top group: 幻獣. Top member: 小豆 Azuki. Market temperature: 61.3. Rising stars: 燁水 Yomizu, DeDe, Meya, Neko, 稲妻莉央. Heat drop watch: none.',
  'pipeline/sync_brain.py'
)
on conflict do nothing;
