"""
pipeline/sync_brain.py

Build a lightweight Secbrain runtime seed from idol-platform outputs.

This script does not require direct database credentials to be useful:
- It reads the current generated insights/rankings
- It writes a SQL seed file that can be applied to the brain schema
- It keeps the knowledge layer aligned with the latest platform state
"""

from __future__ import annotations

import json
from datetime import date
from pathlib import Path


ROOT = Path(__file__).parent.parent
FRONTEND_DATA = ROOT / "frontend-next" / "public" / "data"
INSIGHTS = FRONTEND_DATA / "insights.json"
MEMBERS = FRONTEND_DATA / "member_rankings.json"
GROUPS = FRONTEND_DATA / "v7_rankings.json"
INSIGHT_POSTS = FRONTEND_DATA / "insight_posts.json"
OUT_SQL = ROOT / "supabase" / "seed_brain_runtime.sql"


def sql_text(value: str) -> str:
    return "'" + value.replace("\\", "\\\\").replace("'", "''") + "'"


def sql_array(values: list[str]) -> str:
    escaped = [f'"{value.replace(chr(34), chr(92) + chr(34))}"' for value in values]
    return "array[" + ",".join(sql_text(v.strip('"')) for v in escaped) + "]"


def load_json(path: Path, default):
    if not path.exists():
        return default
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return default


def build_digest() -> dict[str, str]:
    insights = load_json(INSIGHTS, {})
    members = load_json(MEMBERS, [])
    groups = load_json(GROUPS, [])

    generated_at = insights.get("generated_at") or date.today().isoformat()
    highlights = insights.get("weekly_highlights") or {}
    rising = insights.get("rising_stars") or []
    heat_drop = insights.get("heat_drop") or []

    top_member = members[0]["name"] if members else "N/A"
    top_group = highlights.get("top_group") or (groups[0]["display_name"] if groups else "N/A")
    market_temperature = insights.get("market_temperature_v2", insights.get("market_temperature", 0))

    compiled_truth = (
        f"Weekly idol market digest generated on {generated_at}. "
        f"Top group: {top_group}. Top member: {top_member}. "
        f"Market temperature: {market_temperature}. "
        f"Rising stars: {', '.join(rising[:5]) if rising else 'none'}. "
        f"Heat drop watch: {', '.join(heat_drop[:5]) if heat_drop else 'none'}."
    )

    timeline_md = "\n".join(
        [
            f"- {generated_at}: weekly market digest generated",
            f"- Highlight top group: {top_group}",
            f"- Highlight top member: {top_member}",
            f"- Rising stars: {', '.join(rising[:5]) if rising else 'none'}",
        ]
    )

    return {
        "generated_at": str(generated_at),
        "slug": "reports/weekly-market-digest",
        "title": f"Weekly Market Digest {generated_at}",
        "compiled_truth": compiled_truth,
        "timeline_md": timeline_md,
        "top_group": str(top_group),
        "top_member": str(top_member),
        "market_temperature": str(market_temperature),
        "rising_stars": [str(item) for item in rising[:5]],
        "heat_drop": [str(item) for item in heat_drop[:5]],
    }


def render_sql(digest: dict[str, object]) -> str:
    tags = ["idol-platform", "weekly-digest", "ai-insights", "secbrain"]
    frontmatter = json.dumps(
        {
            "generated_at": digest["generated_at"],
            "top_group": digest["top_group"],
            "top_member": digest["top_member"],
            "market_temperature": digest["market_temperature"],
            "rising_stars": digest["rising_stars"],
            "heat_drop": digest["heat_drop"],
        },
        ensure_ascii=False,
    ).replace("'", "''")

    return f"""-- Auto-generated by pipeline/sync_brain.py
insert into brain_pages (slug, type, title, compiled_truth, timeline_md, tags, frontmatter)
values (
  {sql_text(str(digest["slug"]))},
  'source',
  {sql_text(str(digest["title"]))},
  {sql_text(str(digest["compiled_truth"]))},
  {sql_text(str(digest["timeline_md"]))},
  {sql_array(tags)},
  '{frontmatter}'::jsonb
)
on conflict (slug) do update set
  title = excluded.title,
  compiled_truth = excluded.compiled_truth,
  timeline_md = excluded.timeline_md,
  tags = excluded.tags,
  frontmatter = excluded.frontmatter,
  updated_at = now();

insert into brain_timeline_entries (page_slug, entry_date, summary, detail, source)
values (
  {sql_text(str(digest["slug"]))},
  {sql_text(str(digest["generated_at"]))},
  {sql_text(f"Weekly digest refreshed: {digest['generated_at']}")},
  {sql_text(str(digest["compiled_truth"]))},
  'pipeline/sync_brain.py'
)
on conflict do nothing;
"""


def render_insight_post_sql(posts: list[dict[str, object]]) -> str:
    statements: list[str] = []
    for post in posts:
        slug = f"insights/{post['slug']}"
        compiled_truth = " ".join(post.get("content", []))
        timeline_md = f"- {post['date']}: insight published\n- category: {post['category']}"
        frontmatter = json.dumps(
            {
                "source": "frontend-next/public/data/insight_posts.json",
                "category": post["category"],
                "summary": post["summary"],
                "published_at": post["date"],
            },
            ensure_ascii=False,
        ).replace("'", "''")
        statements.append(
            f"""insert into brain_pages (slug, type, title, compiled_truth, timeline_md, tags, frontmatter)
values (
  {sql_text(slug)},
  'source',
  {sql_text(str(post["title"]))},
  {sql_text(compiled_truth)},
  {sql_text(timeline_md)},
  {sql_array(["insight", "idol-platform", str(post["category"])])},
  '{frontmatter}'::jsonb
)
on conflict (slug) do update set
  title = excluded.title,
  compiled_truth = excluded.compiled_truth,
  timeline_md = excluded.timeline_md,
  tags = excluded.tags,
  frontmatter = excluded.frontmatter,
  updated_at = now();
"""
        )
    return "\n".join(statements)


def main():
    digest = build_digest()
    posts = load_json(INSIGHT_POSTS, [])
    sql = render_sql(digest) + "\n" + render_insight_post_sql(posts if isinstance(posts, list) else [])
    OUT_SQL.write_text(sql, encoding="utf-8")
    print(f"Wrote brain runtime seed to {OUT_SQL}")


if __name__ == "__main__":
    main()
